### ISSUE TITLE
GScam doesn't support Tee

### ISSUE THREAD

**Issue by caelinsutch** [clydemcqueen/gscam2#3]
ROS gscam doesn't seem to support Tee, I never have an image stream, nor do I get any error output. Here is the tee that I use, but from research, this seems to be a common thread. A workaround is to launch the tee with a udpsink end in python, and using a udpsrc as my gscam config.

Here is my example gscamconfig with a Tee:
```
nvarguscamerasrc sensor-id=0 ! video/x-raw(memory:NVMM),width=1280,height=720,framerate=15/1 ! nvvidconv flip-method=2 ! tee name=t1 t1. ! queue silent=true ! nvv4l2h264enc bitrate=8000000 ! h264parse config-interval=1 ! queue silent=true leaky=downstream ! rndbuffersize max=65000 ! udpsink host=127.0.0.1 port=5001 sync=false t1. ! video/x-raw, format=BGRx ! videoconvert'
```

Is this a known issue? If so, is there any plan on resolving it?

**Comment by clydemcqueen** [comment]
I was able to get a tee to work in gscam2. I set up 2 instances of gscam_main with different configuration and different topics. The configuration in the first instance is:

cfg_send_and_show = 'v4l2src device=/dev/video1 do-timestamp=true ! queue ! video/x-h264,width=1920,height=1080,framerate=30/1 ! h264parse ! tee name=fork ! queue ! rtph264pay config-interval=10 ! udpsink host=127.0.0.1 port=5600 fork. ! queue ! avdec_h264 ! videoconvert'

In the second instance the configuration is:

cfg_rcv = 'udpsrc port=5600 ! queue ! application/x-rtp ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert'

I'm using this H264 camera: https://bluerobotics.com/store/sensors-sonars-cameras/cameras/cam-usb-low-light-r1/

I also tried a tee that would write to a file, but that did not work. I think the problem is that the file isn't closed correctly. I'm interested in fixing this. I'll file a separate bug.

I did not try this on ROS1.

**Comment by caelinsutch** [comment]
Got it to work, for anyone interested this is what I used:

```
rightConfig = 'nvarguscamerasrc sensor-id=0 ! video/x-raw(memory:NVMM),width=320,height=184,framerate=15/1 ! nvvidconv flip-method=2 ! video/x-raw, format=BGRx ! tee name=fork ! queue silent=true leaky=downstream ! rndbuffersize max=65000 ! udpsink host=127.0.0.1 port=5001 sync=false fork. ! videoconvert'
```

**Comment by caelinsutch** [comment]
I realized last night, that the tee itself that I was using wasn't working even though it worked fine using `gst-launch-1.0`. This is a bug I believe with the `nvv4l2h264enc bitrate=8000000 ! h264parse config-interval=1` part of the pipeline that causes it to hang, @clydemcqueen would you like me to open a new issue for this?

**Comment by clydemcqueen** [comment]
Well... I'm not a gstreamer expert, but I'll try to reproduce this. Can you pose the gst-launch-1.0 string that works, and the gscam config that doesn't?

Also: I don't have a Jetson device, so I haven't used the nvidia gstreamer plugins. Does it hang with other encoders?

**Comment by clydemcqueen** [comment]
@caelinsutch I added some more examples to the README, particularly around composition. I would be happy for feedback and/or a review of the PR. https://github.com/clydemcqueen/gscam2/pull/5

**Comment by caelinsutch** [comment]
@clydemcqueen Here's the pipeline that works using gst-launch:

```
gst-launch-1.0 nvarguscamerasrc sensor-id=0 ! 'video/x-raw(memory:NVMM),width=320,height=184,framerate=15/1' ! nvvidconv flip-method=2 ! tee name=t1 t1. ! queue silent=true ! nvv4l2h264enc bitrate=8000000 ! h264parse config-interval=1 ! queue silent=true leaky=downstream ! rndbuffersize max=65000 ! udpsink host=127.0.0.1 port=5001 sync=false t1. ! queue silent=true ! nvjpegenc ! rtpjpegpay ! udpsink host=127.0.0.1 port=5000 sync=false
```

This gscam config doesn't work:

```
nvarguscamerasrc sensor-id=0 ! 'video/x-raw(memory:NVMM),width=320,height=184,framerate=15/1' ! nvvidconv flip-method=2 ! tee name=t1 t1. ! queue silent=true ! nvv4l2h264enc bitrate=8000000 ! h264parse config-interval=1 ! queue silent=true leaky=downstream ! rndbuffersize max=65000 ! udpsink host=127.0.0.1 port=5001 sync=false t1. ! queue silent=true ! nvjpegenc ! rtpjpegpay
```

To be honest, I'm not sure what encoders to use besides the NVIDIA ones, guidance would be helpful. Any help or guidance would be appreciated :)

Also, slightly off topic, but I see you do some marine robotics. I'd love to talk to you more outside of this, I've sent you a linkedin connection

**Comment by clydemcqueen** [comment]
I think the problem is the last element: `rtpjpegpay` will payload encode jpeg images for transmission, which ROS doesn't understand. If you're going for compressed images try ending with `jpegenc` and set `image_encoding` to "jpeg". Otherwise skip the jpeg encoding and just end with `videoconvert`.

I assume that nvjpegenc is the same as jpegenc, but written to use the Jetson GPU. I'm guessing it will work just as well, but faster.

I don't have a lot of experience with encoding h264, but avenc_h264_omx might be comparable to nvv4l2h264enc.

I don't understand what rndbuffersize max=65000 does.

When debugging pipelines I've found `export GST_DEBUG=4` usually contains information on why the elements fail to negotiate, buried in a mountain of messages.

I hope this helps!

**Comment by caelinsutch** [comment]
Ok thanks for the help! I'll close this issue, not sure why I reopened it considering the problem is fixed with the library!
